name: style

on:
    push:
        branches:
            - main
jobs:
    style:
        name: Style
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout code
                uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

            -   name: Setup PHP
                uses: shivammathur/setup-php@7c071dfe9dc99bdf297fa79cb49ea005b9fcadbc # v2
                with:
                    php-version: 8.3
                    extensions: dom, curl, libxml, mbstring, zip, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
                    coverage: none

            -   name: Install dependencies
                run: composer install

            -   name: Style
                run: composer fix-style

            -   name: Commit Changes
                uses: stefanzweifel/git-auto-commit-action@3ea6ae190baf489ba007f7c92608f33ce20ef04a # v4
                with:
                    commit_message: Fix styling changes
